# Generated by Django 6.0.5 on 2026-05-25 04:07

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='EmissionFactorLibrary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50)),
                ('sub_category', models.CharField(blank=True, max_length=100)),
                ('region', models.CharField(blank=True, max_length=100)),
                ('year', models.IntegerField()),
                ('factor', models.DecimalField(decimal_places=6, max_digits=18)),
                ('unit', models.CharField(max_length=50)),
                ('source', models.CharField(max_length=50)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'unique_together': {('category', 'sub_category', 'region', 'year', 'source')},
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('upload', 'File Uploaded'), ('parse', 'File Parsed'), ('approve', 'Record Approved'), ('reject', 'Record Rejected'), ('edit', 'Record Edited'), ('lock', 'Record Locked'), ('flag', 'Record Auto-Flagged')], max_length=30)),
                ('target_type', models.CharField(blank=True, max_length=30)),
                ('target_id', models.UUIDField(blank=True, null=True)),
                ('detail', models.JSONField(blank=True, default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='emissions.organisation')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='SourceFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_type', models.CharField(choices=[('sap', 'SAP Export (Fuel/Procurement)'), ('utility', 'Utility Data (Electricity)'), ('travel', 'Corporate Travel')], max_length=20)),
                ('file_name', models.CharField(max_length=500)),
                ('file', models.FileField(blank=True, null=True, upload_to='source_files/%Y/%m/')),
                ('raw_content', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('done', 'Done'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('row_count_raw', models.IntegerField(blank=True, null=True)),
                ('row_count_parsed', models.IntegerField(blank=True, null=True)),
                ('row_count_failed', models.IntegerField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('detected_encoding', models.CharField(blank=True, max_length=50)),
                ('detected_delimiter', models.CharField(blank=True, max_length=10)),
                ('parser_version', models.CharField(blank=True, max_length=20)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_files', to='emissions.organisation')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FacilityLookup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sap_plant_code', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=255)),
                ('country_code', models.CharField(blank=True, max_length=3)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('grid_region', models.CharField(blank=True, max_length=100)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facilities', to='emissions.organisation')),
            ],
            options={
                'unique_together': {('organisation', 'sap_plant_code')},
            },
        ),
        migrations.CreateModel(
            name='OrganisationMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('analyst', 'Analyst'), ('admin', 'Admin'), ('auditor', 'Auditor (read-only)')], default='analyst', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='emissions.organisation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'organisation')},
            },
        ),
        migrations.CreateModel(
            name='EmissionRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_row_ref', models.CharField(blank=True, max_length=200)),
                ('scope', models.IntegerField(choices=[(1, 'Scope 1'), (2, 'Scope 2'), (3, 'Scope 3')])),
                ('category', models.CharField(choices=[('fuel_combustion', 'Fuel Combustion'), ('purchased_electricity', 'Purchased Electricity'), ('business_travel_flight', 'Business Travel – Flight'), ('business_travel_hotel', 'Business Travel – Hotel'), ('business_travel_ground', 'Business Travel – Ground Transport'), ('procurement', 'Procurement')], max_length=50)),
                ('activity_date', models.DateField()),
                ('period_start', models.DateField(blank=True, null=True)),
                ('period_end', models.DateField(blank=True, null=True)),
                ('raw_quantity', models.DecimalField(decimal_places=4, max_digits=18)),
                ('raw_unit', models.CharField(max_length=50)),
                ('raw_currency', models.CharField(blank=True, max_length=10)),
                ('raw_spend', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('normalised_quantity', models.DecimalField(decimal_places=4, max_digits=18)),
                ('normalised_unit', models.CharField(max_length=50)),
                ('emission_factor', models.DecimalField(decimal_places=6, max_digits=18)),
                ('emission_factor_source', models.CharField(blank=True, max_length=200)),
                ('emission_factor_year', models.IntegerField(blank=True, null=True)),
                ('co2e_kg', models.DecimalField(decimal_places=4, max_digits=18)),
                ('facility_code', models.CharField(blank=True, max_length=100)),
                ('facility_name', models.CharField(blank=True, max_length=255)),
                ('country_code', models.CharField(blank=True, max_length=3)),
                ('source_metadata', models.JSONField(blank=True, default=dict)),
                ('validation_flags', models.JSONField(blank=True, default=list)),
                ('is_estimated', models.BooleanField(default=False)),
                ('estimation_note', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('flagged', 'Flagged'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('locked', 'Locked for Audit')], default='pending', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_note', models.TextField(blank=True)),
                ('is_edited', models.BooleanField(default=False)),
                ('original_values', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_records', to=settings.AUTH_USER_MODEL)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emission_records', to='emissions.organisation')),
                ('source_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='emissions.sourcefile')),
            ],
            options={
                'ordering': ['-activity_date'],
                'indexes': [models.Index(fields=['organisation', 'scope', 'activity_date'], name='emissions_e_organis_63a65f_idx'), models.Index(fields=['organisation', 'status'], name='emissions_e_organis_82179a_idx'), models.Index(fields=['source_file'], name='emissions_e_source__8dd5e6_idx')],
            },
        ),
    ]
